[project]
name = "pypolyclip"
description = "A python driver to the polyclip functions"
dynamic = [
    "version"
]

[build-system]
requires = ["setuptools", "wheel", "numpy"]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-astropy",
    "pytest-tornasync",
    "matplotlib"
]