name: Weekly Cron Tests

on:
  schedule:
    # run every Monday at 9am UTC
    - cron: '0 9 * * 1'
  push:
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TOXARGS: '-v'

permissions:
  contents: read

jobs:
  ci_cron_tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    if: github.repository == 'spacetelescope/pypolyclip'
    strategy:
      matrix:
        include:
          - name: Python 3.11 (linux)
            os: ubuntu-latest
            python: '3.11'
            toxenv: py311-test
            toxposargs: --run-slow
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }} on ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: python -m pip install --upgrade pip tox
    - name: Test with tox
      run: tox -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
