# GitHub Actions workflow that runs on a cron schedule.
name: Cron Scheduled CI Tests

on:
  workflow_dispatch:
  schedule:
    # run at 9am UTC on Mondays
    - cron: '0 9 * * 1'

permissions:
  contents: read

jobs:
  # The linkcheck job tests that the links in the docs point to real places
  # The if statement is to prevent cron from running on forks.
  linkcheck:
    runs-on: ubuntu-latest
    if: github.repository == 'spacetelescope/pypolyclip'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python to build docs with sphinx
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Check links in docs using tox
      run: tox -e linkcheck

  ci_cron_tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    if: github.repository == 'spacetelescope/pypolyclip'
    matrix:
      include:
        # NOTE: we don't have devdeps here
        - name: Python 3.11
          os: ubuntu-latest
          python: 3.11
          toxenv: py311-test
          toxposargs: --run-slow

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up python ${{ matrix.python }} on ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Test with tox
      run: tox -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
